/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_puzzle_MainActivity2 */

#ifndef _Included_com_example_puzzle_MainActivity2
#define _Included_com_example_puzzle_MainActivity2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_puzzle_MainActivity2
 * Method:    openDriver
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_puzzle_MainActivity2_openDriver
  (JNIEnv *, jobject);

/*
 * Class:     com_example_puzzle_MainActivity2
 * Method:    writeDriver
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_puzzle_MainActivity2_writeDriver
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_puzzle_MainActivity2
 * Method:    readDriver
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_puzzle_MainActivity2_readDriver
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_puzzle_MainActivity2
 * Method:    closeDriver
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_puzzle_MainActivity2_closeDriver
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
