/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_puzzle_MainActivity2_ReadThread */

#ifndef _Included_com_example_puzzle_MainActivity2_ReadThread
#define _Included_com_example_puzzle_MainActivity2_ReadThread
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_puzzle_MainActivity2_ReadThread_MIN_PRIORITY
#define com_example_puzzle_MainActivity2_ReadThread_MIN_PRIORITY 1L
#undef com_example_puzzle_MainActivity2_ReadThread_NORM_PRIORITY
#define com_example_puzzle_MainActivity2_ReadThread_NORM_PRIORITY 5L
#undef com_example_puzzle_MainActivity2_ReadThread_MAX_PRIORITY
#define com_example_puzzle_MainActivity2_ReadThread_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
